In [101]:
# # mount it
# from google.colab import drive
# drive.mount('/content/drive')
# # copy it there
# !mkdir -p /content/final_project/data/
# !cp -f /content/drive/MyDrive/ece1786/final_project/data/NLP_Labelled_Data_Company_v4.xlsx /content/final_project/data/

In [102]:
import pandas as pd
# This dataset is manually collected by selecting descriptions related to company's operations 
# from the 2021 annual reports found on company's public sites.  
# Primary labels are basic off the company's GICS code, which is widely reconigzed by the indsutry.
# Additional labels are created manually when reading the descriptions by considerating
# GICS standard: https://www.spglobal.com/marketintelligence/en/documents/112727-gics-mapbook_2018_v3_letter_digitalspreads.pdf

data = pd.read_excel("final_project/data/NLP_Labelled_Data_Company_v4.xlsx", sheet_name=2)
data = data[data["Ready"] == "Y"].dropna(subset=['Annual Report Description'])
data['WordCount'] = data['Annual Report Description'].apply(lambda n: len(n.split()))
columns = ["Ticker", "CompanyName", "IndustryGroupId", "IndustryGroup", "AdditionalLabel1", "AdditionalLabel2", "AdditionalLabel3", "Annual Report Description", "WordCount"]
data = data[columns]
data.shape

(191, 9)

In [103]:
label_ls = ['Automobiles & Components','Banks','Capital Goods',
 'Commercial & Professional Services','Consumer Durables & Apparel',
 'Consumer Services','Diversified Financials','Energy',
 'Food & Staples Retailing','Food, Beverage & Tobacco',
 'Health Care Equipment & Services','Household & Personal Products',
 'Insurance','Materials','Media & Entertainment',
 'Pharmaceuticals, Biotechnology & Life Sciences','Real Estate',
 'Retailing','Semiconductors & Semiconductor Equipment',
 'Software & Services','Technology Hardware & Equipment',
 'Telecommunication Services','Transportation','Utilities']
len(label_ls)

24

In [104]:
# Some quality checks
# All labesl are done properly
assert(data[data["IndustryGroup"].isin(label_ls)].shape == data.shape)
assert(data[data["AdditionalLabel1"].isin(label_ls) | data["AdditionalLabel1"].isna()].shape == data.shape)
assert(data[data["AdditionalLabel2"].isin(label_ls) | data["AdditionalLabel2"].isna()].shape == data.shape)
assert(data[data["AdditionalLabel3"].isin(label_ls) | data["AdditionalLabel3"].isna()].shape == data.shape)

# Make sure we have all labels included
assert(len(data["IndustryGroup"].unique()) == len(label_ls))

In [105]:
# Combined all possible labels into a single column, and remove all nan from each sublist
industry_group_list = data[["IndustryGroup", "AdditionalLabel1", "AdditionalLabel2", "AdditionalLabel3"]].values.tolist()
industry_group_list = [[item for item in row if item == item] for row in industry_group_list]
data["industry_group"] = industry_group_list

In [106]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MultiLabelBinarizer # for multi labels https://www.projectpro.io/recipes/one-hot-encoding-with-multiple-labels-in-python
from numpy import array

# Create one-hot labels
X = data["Annual Report Description"]
y = data["industry_group"]

one_hot = MultiLabelBinarizer()
labels = one_hot.fit_transform(y)
print(labels)
# print(one_hot.classes_)
data['labels'] = list(labels)
data


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Ticker             CompanyName  IndustryGroupId  \
9     ATVI     Activision Blizzard             5020   
10    ATVI     Activision Blizzard             5020   
14     AES                AES Corp             5510   
15     AFL               AFLAC Inc             4030   
16     AFL               AFLAC Inc             4030   
..     ...                     ...              ...   
586     VZ  Verizon Communications             5010   
597    WMT                 Walmart             3010   
598    WMT                 Walmart             3010   
611    WHR         Whirlpool Corp.             2520   
612    WHR         Whirlpool Corp.             2520   

                   IndustryGroup     AdditionalLabel1 AdditionalLabel2  \
9          Media & Entertainment  Software & Services              NaN   
10         Media & Entertainment  Software & Services              NaN   
14                     Utilities          Real Estate              NaN   
15                     Insurance                  NaN              NaN   
16                     Insurance                  NaN              NaN   
..                           ...                  ...              ...   
586   Telecommunication Services                  NaN              NaN   
597     Food & Staples Retailing                  NaN              NaN   
598     Food & Staples Retailing                  NaN              NaN   
611  Consumer Durables & Apparel                  NaN              NaN   
612  Consumer Durables & Apparel                  NaN              NaN   

     AdditionalLabel3                          Annual Report Description  \
9                 NaN  We develop interactive entertainment content a...   
10                NaN  Activision Blizzard, Inc. is a leading global ...   
14                NaN  Incorporated in 1981, AES is a global energy c...   
15                NaN  Aflac Japan is the principal contributor to th...   
16                NaN  Aflac Incorporated was incorporated in 1973 un...   
..                ...                                                ...   
586               NaN  Verizon Communications Inc. (Verizon or the Co...   
597               NaN  Our strategy is to make every day easier for b...   
598               NaN  Sam's Club operates in 44 states in the U.S. a...   
611               NaN  As a 110-year old company with a legacy of suc...   
612               NaN  As the shift to digital continues, consumers c...   

     WordCount                                industry_group  \
9          233  [Media & Entertainment, Software & Services]   
10         306  [Media & Entertainment, Software & Services]   
14         355                      [Utilities, Real Estate]   
15         261                                   [Insurance]   
16         272                                   [Insurance]   
..         ...                                           ...   
586        292                  [Telecommunication Services]   
597        296                    [Food & Staples Retailing]   
598        299                    [Food & Staples Retailing]   
611        212                 [Consumer Durables & Apparel]   
612        276                 [Consumer Durables & Apparel]   

                                                labels  
9    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
10   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
14   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
15   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...  
16   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...  
..                                                 ...  
586  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
597  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...  
598  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...  
611  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
612  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[191 rows x 11 columns]